services:
  mariadb:
    container_name: mariadb
    restart: always
    expose: "3306"
    env_file: .env
    build:
      context: ./requirements/mariadb
    volumes:
      - mariadbVol:/var/lib/mysql
    secrets:
      - mysql_root_password
      - mysql_password
    networks:
      - inception_network

  wordpress:
    container_name: wordpress
    restart: always
    expose: "9000"
    env_file: .env
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
    volumes: 
      - wordpressVol:/var/www/html
    networks:
      - inception_network

  nginx:
    container_name: nginx
    restart: always
    ports: "443:443"
    env_file: .env
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
    volumes:
      - wordpressVol:/var/www/html
    networks:
      - inception_network

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  mysql_password:
    file: ./secrets/mysql_password.txt

networks:
  inception_network:
    driver: bridge

volumes:
  mariadbVol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/relvan/data/mariadb

  wordpressVol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/relvan/data/wordpress
