version: '3.7'

services:
  mariadb:
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    env_file: .env
    volumes:
      - mariadbVol:/var/lib/mysql
    networks:
      - inception-network
    expose:
      - "3306"
    restart: always

  wordpress:
    image: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpressVol:/var/www/html
    networks:
      - inception-network
    expose:
      - "9000"
    restart: always
    depends_on:
      - mariadb

  nginx:
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - wordpressVol:/var/www/html
    networks:
      - inception-network
    restart: always
    depends_on:
      - wordpress

networks:
  inception-network:
    driver: bridge
    name: inception-network

volumes:
  mariadbVol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/relvan/data/mariadb
  wordpressVol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/relvan/data/wordpress
